### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by AndreaCrotti** [iwoca/django-deep-collector#19]
There is an issue with Django 1.9, probably simple to fix

    from django.utils.deprecation import RemovedInDjango19Warning
    ImportError: cannot import name RemovedInDjango19Warning

**Comment by romgar** [comment]
I have not yet released the latest version of `django-deep-collector` that is Django 1.9 compatible. I will do it now.
That will fix your problem,

**Comment by AndreaCrotti** [comment]
Thanks!
