### ISSUE TITLE
Collecting Generic Foreign Key

### ISSUE THREAD

**Issue by MiiRaGe** [iwoca/django-deep-collector#21]
Hi,

Apparently DDC does not collect generic foreign key :/

Is it something you plan to support ? :)

**Comment by romgar** [comment]
Hi @MiiRaGe !

It will definitely be supported. I will work on it !

**Comment by romgar** [comment]
@MiiRaGe I have added `GenericForeignKey` support. You can test it in `generic_foreign_key_handling` branch. I still have some refactoring to do before merging it to main branch, but it should work properly.

Pay attention that if you want to collect objects on a "reverse" way, you should explicitly define `GenericRelation` field in the model that is pointed by a `GenericForeignKey`. See `tests.test_core.TestGFKRelation` for more informations.

**Comment by romgar** [comment]
Merged to main branch.
