### ISSUE TITLE
support django >= 2.0 ?

### ISSUE THREAD

**Issue by kobayashi** [iwoca/django-deep-collector#35]
Hi,

Does this package still not support Django 2.0 ?
I have following error with my environment.

```
>>> ip = Ipaadress.objects.get(id=1)
>>> ip
<Ipaddress: 192.168.1.1>
>>> collector = RelatedObjectsCollector()
>>> collector.collect(ip)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/kobayashi/.virtualenvs/foo/lib/python3.6/site-packages/deep_collector/core.py", line 268, in collect
    children = self._collect(parent, obj)
  File "/Users/kobayashi/.virtualenvs/foo/lib/python3.6/site-packages/deep_collector/core.py", line 323, in _collect
    self.post_collect(obj)
  File "/Users/kobayashi/.virtualenvs/foo/lib/python3.6/site-packages/deep_collector/core.py", line 347, in post_collect
    if isinstance(field, ForeignKey) and not field.unique and field.rel.to == type(self.root_obj):
AttributeError: 'ForeignKey' object has no attribute 'rel'
```

Here is my setup.
```
$ pip freeze |grep Django
Django==2.0.5

$ pip freeze |grep deep-collector
django-deep-collector==0.4.2

```

**Comment by tzetter** [comment]
It seems like the last release was made in 2016, while Django 2 support was added only 6 months ago. 

Are there any plans to do a new release?

**Comment by romgar** [comment]
@walkbase there was no plan to upgrade it in the next weeks, but PRs are welcome :-)

**Comment by tzetter** [comment]
There is already support for Django 2.0 in the develop branch, so I'm not really requesting any changes to the project.

The issue the author here has is it that he's using the latest version available in PyPI (0.4.2), which is outdated. It would be great if someone from the team could create a new release and push it to PyPI, so that those using Django 2+ can use the project without installing from git.

**Comment by romgar** [comment]
You are correct @tzetter ! Will update the change log and release it on PyPI asap, most likely in the next week or two.

**Comment by romgar** [comment]
@kobayashi @tzetter I was a bit busier than initially anticipated, sorry about that. Version `0.5.0` finally released on PyPI!
