### ISSUE TITLE
PyPI upload failed

### ISSUE THREAD

**Issue by nesaro** [iwoca/django-deep-collector#39]
Travis' deploy pipelines are failing https://travis-ci.org/github/iwoca/django-deep-collector/jobs/765482723

Probably some credentials or configuration issue

**Comment by tzetter** [comment]
My theory would be that the version number has to be changed in `setup.py`. The output still mentions version 0.5.0 and the error "File already exists."

**Comment by momirza** [comment]
I deleted the `0.6.0` tag, updated the version in `setup.py` and tagged that as `0.6.0`.

**Comment by momirza** [comment]
Ok I can see the release on pypi now so closing this.
