### ISSUE TITLE
How to collect only dependent objects?

### ISSUE THREAD

**Issue by MartinSchmidt123** [iwoca/django-deep-collector#40]
Thanks for creating this project.
It works really well.

Let me briefly explain my use case: Before deleting an object A I want to show a preview of all dependent objects that will be affected by the deletion (depending on the on_delete parameter). 
In terms of the README, I am interested in all 'related' fields but not the 'direct' fields.

I have an existing code base with a large number of classes that makes excluding all individual fields via EXCLUDE_DIRECT_FIELDS cumbersome.
Currently, I am patching the `get_local_objs()` method in https://github.com/iwoca/django-deep-collector/blob/0.6.0/deep_collector/core.py#L368 to always return an empty list `[]`.

Is there a way to disable collecting objects via 'direct' fields?
Is this a valid use case of this project or can you recommend another solution?

**Comment by momirza** [comment]
Hi, thanks for reaching out. 

If you are only interested in related fields, I won't be too difficult to add a boolean flag to `EXCLUDE_ALL_DIRECT_FIELDS`. 

Does that work? Feel free to open a PR with that or an alternative solution and I'll be happy to review. 😃
